# Generated by Django 5.2.6 on 2025-11-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_parkingpass_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingpass',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI')], default='cash', max_length=10),
        ),
    ]
